[uwsgi]
chdir = /app
module = config.wsgi:application
master = true
enable-threads = true
need-app = true
lazy-apps = true
vacuum = true
die-on-term = true
http = 0.0.0.0:$(PORT)
http-timeout = 300
harakiri = 300
buffer-size = 65535
