[uwsgi]
chdir = /app
module = config.wsgi:application
master = true
enable-threads = true
need-app = true
lazy-apps = true
vacuum = true
die-on-term = true
http = 0.0.0.0:$(PORT)
http-timeout = 300
http-keepalive = 1
http-auto-chunked = true
add-header = X-Accel-Buffering: no
add-header = Connection: keep-alive
die-on-term = true
memory-report = true
# Desactiva buffering interno de uwsgi para que los datos fluyan a Cloud Run
http-manage-expect = true
chunked-input-timeout = 300
# Importante para Cloud Run: no bufferizar el cuerpo si es streaming
post-buffering = 0
manage-script-name = true
